language: java
jdk:
- oraclejdk8
addons:
  ssh_known_hosts: lolcat.passoire.net
before_deploy:
- openssl aes-256-cbc -K $encrypted_126fca130ef5_key -iv $encrypted_126fca130ef5_iv -in id_rsa.enc -out id_rsa -d
- chmod 600 id_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: scp -i id_rsa target/simple-api-*.jar lolcat@lolcat.passoire.net:~/simple-api.jar
  on:
    branch: master
